-- ==============================================================================
-- EXAMSARTHI — Seed Data
-- ==============================================================================
-- Populates Master Question Bank (36 questions), Competitive Mock Exams (e1..e3),
-- and Subject Practice Sets (p1..p5) with deterministic cohort mappings.
-- ==============================================================================

-- 1. SEED EXAMS & PRACTICE SETS
INSERT INTO public.exams (id, title, category, subject, description, duration_minutes, difficulty, total_questions, is_active)
VALUES
  ('e1', 'SSC CGL Tier 1 Mock', 'mock', 'Reasoning, GA, Quant & English', 'Complete 4-section simulation based on the latest pattern: Reasoning, GA, Quant, and English.', 15, 'Intermediate', 12, true),
  ('e2', 'Banking Prelims', 'mock', 'Quant, Reasoning & English', 'High-speed simulation for IBPS and SBI prelims covering Quant, Reasoning Ability, and English.', 15, 'Advanced', 12, true),
  ('e3', 'UPSC CSAT Foundation', 'mock', 'Reasoning, Quant & Reading Comprehension', 'Paper II civil services simulation covering Logical Reasoning, Basic Numeracy, and English Comprehension.', 15, 'Intermediate', 9, true),
  ('p1', 'Percentages, Ratios & Arithmetic', 'practice', 'Quantitative Aptitude', 'Focused practice in percentages, simple interest, time and distance, and ratios across accessible formats.', 10, 'Beginner', 8, true),
  ('p2', 'General Knowledge & Geography', 'practice', 'General Knowledge', 'Essential constitutional articles, history, science, geography, and economy with accessible question types.', 10, 'Intermediate', 8, true),
  ('p3', 'Logical Reasoning & Coding', 'practice', 'Reasoning', 'Deductive logic, number series, blood relations, and syllogisms across diverse question formats.', 10, 'Advanced', 8, true),
  ('p4', 'English Grammar & Comprehension', 'practice', 'English', 'Rules of grammar, vocabulary, error detection, spelling, and preposition usage.', 10, 'Intermediate', 8, true),
  ('p5', 'Accessible Multi-Format Showcase', 'practice', 'Multi-Format Showcase', 'Curated session testing all 5 accessible question types: Single Choice, Multiple Choice, True/False, Short Answer, and Fill in the Blank.', 8, 'Beginner', 5, true)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  category = EXCLUDED.category,
  subject = EXCLUDED.subject,
  description = EXCLUDED.description,
  duration_minutes = EXCLUDED.duration_minutes,
  difficulty = EXCLUDED.difficulty,
  total_questions = EXCLUDED.total_questions,
  is_active = EXCLUDED.is_active;

-- 2. SEED MASTER QUESTION BANK (36 Questions across 5 Formats)
INSERT INTO public.questions (id, type, text, subject, topic, difficulty, options, correct_answer, acceptable_answers, explanation)
VALUES
  ('quant-1', 'single-choice', 'If the price of a commodity decreases by 20% and its consumption increases by 25%, what is the net percentage change in expenditure?', 'Quantitative Aptitude', 'Percentages', 'Intermediate', '[{"id":"qo-1","text":"No change (0%)"},{"id":"qo-2","text":"4% decrease"},{"id":"qo-3","text":"5% increase"},{"id":"qo-4","text":"2% decrease"}]'::jsonb, '"qo-1"'::jsonb, NULL, 'Let initial expenditure be 100. New expenditure = (100 - 20) * (1 + 0.25) = 80 * 1.25 = 100. Net change is 0%.'),
  ('quant-2', 'single-choice', 'A train running at a speed of 72 km/h crosses a 250 m long platform in 20 seconds. What is the length of the train?', 'Quantitative Aptitude', 'Time and Distance', 'Beginner', '[{"id":"qo-5","text":"120 metres"},{"id":"qo-6","text":"150 metres"},{"id":"qo-7","text":"180 metres"},{"id":"qo-8","text":"200 metres"}]'::jsonb, '"qo-6"'::jsonb, NULL, 'Speed in m/s = 72 * (5/18) = 20 m/s. Total distance = Speed * Time = 20 * 20 = 400 m. Train length = 400 - 250 = 150 metres.'),
  ('quant-3', 'single-choice', 'The ratio of two positive numbers is 3:4 and their HCF is 4. What is their Lowest Common Multiple (LCM)?', 'Quantitative Aptitude', 'Ratio and Proportion', 'Intermediate', '[{"id":"qo-9","text":"12"},{"id":"qo-10","text":"24"},{"id":"qo-11","text":"36"},{"id":"qo-12","text":"48"}]'::jsonb, '"qo-12"'::jsonb, NULL, 'The numbers are 3 * 4 = 12 and 4 * 4 = 16. LCM(12, 16) = 48.'),
  ('quant-4', 'single-choice', 'A sum of money invested at simple interest amounts to Rs. 815 in 3 years and to Rs. 854 in 4 years. What is the original principal sum?', 'Quantitative Aptitude', 'Simple Interest', 'Advanced', '[{"id":"qo-13","text":"Rs. 650"},{"id":"qo-14","text":"Rs. 690"},{"id":"qo-15","text":"Rs. 698"},{"id":"qo-16","text":"Rs. 700"}]'::jsonb, '"qo-15"'::jsonb, NULL, 'Simple interest for 1 year = 854 - 815 = Rs. 39. Interest for 3 years = 39 * 3 = Rs. 117. Principal = 815 - 117 = Rs. 698.'),
  ('quant-5', 'multiple-choice', 'Which of the following numbers are prime numbers? (Select all that apply)', 'Quantitative Aptitude', 'Number Systems', 'Beginner', '[{"id":"qo-17","text":"29"},{"id":"qo-18","text":"33"},{"id":"qo-19","text":"37"},{"id":"qo-20","text":"49"}]'::jsonb, '["qo-17","qo-19"]'::jsonb, NULL, '29 and 37 are prime numbers as their only divisors are 1 and themselves. 33 is divisible by 3 and 11; 49 is divisible by 7.'),
  ('quant-6', 'multiple-choice', 'Which of the following statements regarding integers and numbers are mathematically correct? (Select all that apply)', 'Quantitative Aptitude', 'Number Systems', 'Intermediate', '[{"id":"qo-21","text":"The product of two negative integers is always positive"},{"id":"qo-22","text":"Every natural number is a whole number"},{"id":"qo-23","text":"Zero is an odd integer"},{"id":"qo-24","text":"The sum of any two odd integers is always an even integer"}]'::jsonb, '["qo-21","qo-22","qo-24"]'::jsonb, NULL, 'Product of negative integers is positive. Whole numbers include all natural numbers plus 0. Zero is an even number. Sum of two odd integers (2a+1 + 2b+1 = 2(a+b+1)) is always even.'),
  ('quant-7', 'true-false', 'In standard arithmetic and real analysis, zero (0) is classified as a positive integer.', 'Quantitative Aptitude', 'Number Systems', 'Beginner', NULL, 'false'::jsonb, NULL, 'False. Zero is neither positive nor negative; it is a sign-neutral integer.'),
  ('quant-8', 'true-false', 'In Euclidean planar geometry, the sum of all three interior angles of any triangle is always strictly equal to 180 degrees.', 'Quantitative Aptitude', 'Geometry', 'Beginner', NULL, 'true'::jsonb, NULL, 'True. In Euclidean plane geometry, the sum of internal angles of any planar triangle is exactly 180°.'),
  ('quant-9', 'short-answer', 'What is the square root of 625?', 'Quantitative Aptitude', 'Arithmetic', 'Beginner', NULL, '"25"'::jsonb, '["25","twenty five","twenty-five"]'::jsonb, '25 * 25 = 625. Thus the principal square root is 25.'),
  ('quant-10', 'fill-blank', 'A triangle in which all three sides are of equal length and all interior angles measure 60 degrees is called an ___ triangle.', 'Quantitative Aptitude', 'Geometry', 'Beginner', NULL, '"Equilateral"'::jsonb, '["Equilateral","equilateral triangle","equilateral"]'::jsonb, 'An equilateral triangle has all three sides congruent and internal angles equal to 60 degrees.'),
  ('reason-1', 'single-choice', 'Select the related word from the given alternatives: Ocean : Water :: Glacier : ?', 'Reasoning', 'Analogy', 'Beginner', '[{"id":"ro-1","text":"Mountain"},{"id":"ro-2","text":"Ice"},{"id":"ro-3","text":"Cave"},{"id":"ro-4","text":"River"}]'::jsonb, '"ro-2"'::jsonb, NULL, 'As an ocean consists primarily of water, a glacier consists of solid ice.'),
  ('reason-2', 'single-choice', 'Find the missing number in the sequence: 3, 8, 15, 24, 35, ?', 'Reasoning', 'Series', 'Intermediate', '[{"id":"ro-5","text":"46"},{"id":"ro-6","text":"48"},{"id":"ro-7","text":"50"},{"id":"ro-8","text":"52"}]'::jsonb, '"ro-6"'::jsonb, NULL, 'Pattern is n^2 - 1 for n = 2, 3, 4, 5, 6, 7. For n = 7: 7^2 - 1 = 49 - 1 = 48.'),
  ('reason-3', 'single-choice', 'Pointing to a photograph, a man said, ''I have no brother or sister, but that man''s father is my father''s son.'' Whose photograph was it?', 'Reasoning', 'Blood Relations', 'Intermediate', '[{"id":"ro-9","text":"His own"},{"id":"ro-10","text":"His son''s"},{"id":"ro-11","text":"His father''s"},{"id":"ro-12","text":"His nephew''s"}]'::jsonb, '"ro-10"'::jsonb, NULL, 'Since the speaker has no siblings, ''my father''s son'' is the speaker himself. Thus ''that man''s father is me'', making it his son''s photograph.'),
  ('reason-4', 'single-choice', 'If ''DELHI'' is coded as ''73541'' and ''CALCUTTA'' as ''82589662'', how can ''CALICUT'' be coded in this numerical system?', 'Reasoning', 'Coding and Decoding', 'Beginner', '[{"id":"ro-13","text":"5279431"},{"id":"ro-14","text":"5978213"},{"id":"ro-15","text":"8251896"},{"id":"ro-16","text":"8543261"}]'::jsonb, '"ro-15"'::jsonb, NULL, 'Letter map: C=8, A=2, L=5, I=1, C=8, U=9, T=6. Result = 8251896.'),
  ('reason-5', 'multiple-choice', 'Given Statements: (I) All roses are flowers. (II) All flowers are plants. Which of the following conclusions logically follow? (Select all that apply)', 'Reasoning', 'Syllogisms', 'Intermediate', '[{"id":"ro-17","text":"All roses are plants"},{"id":"ro-18","text":"Some plants are flowers"},{"id":"ro-19","text":"All plants are roses"},{"id":"ro-20","text":"Some flowers are roses"}]'::jsonb, '["ro-17","ro-18","ro-20"]'::jsonb, NULL, 'By transitivity, All roses are plants. By conversion, Some plants are flowers, and Some flowers are roses. ''All plants are roses'' is an invalid universal deduction.'),
  ('reason-6', 'true-false', 'In deductive logic: If all squares are rectangles, and all rectangles are polygons, then every square is necessarily a polygon.', 'Reasoning', 'Deductive Logic', 'Beginner', NULL, 'true'::jsonb, NULL, 'True. The transitive rule of universal categorical syllogisms states that (A ⊆ B) and (B ⊆ C) logically entails (A ⊆ C).'),
  ('reason-7', 'short-answer', 'In a class of 40 students, Rohan''s rank is 15th from the top. What is his rank from the bottom?', 'Reasoning', 'Ranking and Order', 'Beginner', NULL, '"26"'::jsonb, '["26","26th","twenty six","twenty-sixth"]'::jsonb, 'Rank from bottom = Total students - Rank from top + 1 = 40 - 15 + 1 = 26th.'),
  ('reason-8', 'fill-blank', 'Complete the alphabet letter series: A, C, F, J, ___ (Difference increments by +2, +3, +4, +5).', 'Reasoning', 'Series', 'Beginner', NULL, '"O"'::jsonb, '["O","o"]'::jsonb, 'Position sequence: A(1) + 2 = C(3); C(3) + 3 = F(6); F(6) + 4 = J(10); J(10) + 5 = O(15). The next letter is O.'),
  ('eng-1', 'single-choice', 'Choose the correct synonym for the capitalized word: ''ABUNDANT''.', 'English', 'Vocabulary', 'Beginner', '[{"id":"eo-1","text":"Scarce"},{"id":"eo-2","text":"Plentiful"},{"id":"eo-3","text":"Rare"},{"id":"eo-4","text":"Limited"}]'::jsonb, '"eo-2"'::jsonb, NULL, '''Abundant'' means existing or available in large quantities; plentiful.'),
  ('eng-2', 'single-choice', 'Identify the segment containing a grammatical error: ''Neither of the two candidates have submitted their verification documents.''', 'English', 'Grammar', 'Intermediate', '[{"id":"eo-5","text":"Neither of"},{"id":"eo-6","text":"the two candidates"},{"id":"eo-7","text":"have submitted"},{"id":"eo-8","text":"their verification documents"}]'::jsonb, '"eo-7"'::jsonb, NULL, 'The subject ''Neither'' is singular, requiring the singular auxiliary verb ''has submitted'' instead of ''have submitted''.'),
  ('eng-3', 'single-choice', 'Select the correctly spelt word from the options.', 'English', 'Spelling', 'Advanced', '[{"id":"eo-9","text":"Accommodate"},{"id":"eo-10","text":"Acommodate"},{"id":"eo-11","text":"Accomodate"},{"id":"eo-12","text":"Acomodate"}]'::jsonb, '"eo-9"'::jsonb, NULL, '''Accommodate'' is correctly spelled with double ''c'' and double ''m''.'),
  ('eng-4', 'single-choice', 'Select the word that is the most appropriate ANTONYM for ''METICULOUS''.', 'English', 'Vocabulary', 'Intermediate', '[{"id":"eo-13","text":"Careless"},{"id":"eo-14","text":"Thorough"},{"id":"eo-15","text":"Detailed"},{"id":"eo-16","text":"Diligent"}]'::jsonb, '"eo-13"'::jsonb, NULL, '''Meticulous'' means showing great attention to detail. Its opposite is ''careless''.'),
  ('eng-5', 'multiple-choice', 'In which of the following sentences does the word ''fast'' function as an ADVERB? (Select all that apply)', 'English', 'Parts of Speech', 'Advanced', '[{"id":"eo-17","text":"She ran very fast to catch the morning train"},{"id":"eo-18","text":"He was a fast runner during his college years"},{"id":"eo-19","text":"The ship was held fast in the thick polar ice"},{"id":"eo-20","text":"They observed a strict dawn-to-dusk fast"}]'::jsonb, '["eo-17","eo-19"]'::jsonb, NULL, 'In ''ran fast'' and ''held fast'', ''fast'' modifies verbs (''ran'' and ''held'') as an adverb. In ''fast runner'' it is an adjective, and in ''observed a fast'' it is a noun.'),
  ('eng-6', 'true-false', 'In English grammar, a sentence formed in the passive voice must always contain the past participle (V3) form of the main verb.', 'English', 'Grammar', 'Beginner', NULL, 'true'::jsonb, NULL, 'True. All passive voice constructions require a form of the auxiliary ''to be'' followed by the past participle (V3) of the main verb.'),
  ('eng-7', 'short-answer', 'Provide the one-word substitution for: ''A person who collects or has a great love for books''.', 'English', 'Vocabulary', 'Beginner', NULL, '"Bibliophile"'::jsonb, '["Bibliophile","bibliophile","book lover"]'::jsonb, 'A bibliophile is an enthusiastic book collector or lover.'),
  ('eng-8', 'fill-blank', 'The executive committee unanimously agreed ___ the new accessibility recommendations submitted by the panel.', 'English', 'Prepositions', 'Intermediate', NULL, '"to"'::jsonb, '["to","upon","with"]'::jsonb, 'One agrees ''to'' a proposal/plan, ''with'' a person, and ''on/upon'' a topic after deliberation.'),
  ('gk-1', 'single-choice', 'Which city is the administrative capital of the Indian state of Madhya Pradesh?', 'General Knowledge', 'Geography', 'Beginner', '[{"id":"go-1","text":"Indore"},{"id":"go-2","text":"Bhopal"},{"id":"go-3","text":"Jabalpur"},{"id":"go-4","text":"Gwalior"}]'::jsonb, '"go-2"'::jsonb, NULL, 'Bhopal is the capital city of Madhya Pradesh.'),
  ('gk-2', 'single-choice', 'Who served as the Chairman of the Drafting Committee of the Constituent Assembly of India?', 'General Knowledge', 'Polity', 'Beginner', '[{"id":"go-5","text":"Mahatma Gandhi"},{"id":"go-6","text":"Jawaharlal Nehru"},{"id":"go-7","text":"B. R. Ambedkar"},{"id":"go-8","text":"Sardar Vallabhbhai Patel"}]'::jsonb, '"go-7"'::jsonb, NULL, 'Dr. B. R. Ambedkar was the Chairman of the Drafting Committee of the Indian Constitution.'),
  ('gk-3', 'single-choice', 'Which planet in our solar system is commonly designated as the ''Red Planet''?', 'General Knowledge', 'Science', 'Beginner', '[{"id":"go-9","text":"Venus"},{"id":"go-10","text":"Jupiter"},{"id":"go-11","text":"Saturn"},{"id":"go-12","text":"Mars"}]'::jsonb, '"go-12"'::jsonb, NULL, 'Mars appears reddish due to the prevalence of iron oxide on its surface.'),
  ('gk-4', 'single-choice', 'The Reserve Bank of India (RBI) was established on April 1 of which year?', 'General Knowledge', 'Economy', 'Intermediate', '[{"id":"go-13","text":"1935"},{"id":"go-14","text":"1947"},{"id":"go-15","text":"1950"},{"id":"go-16","text":"1955"}]'::jsonb, '"go-13"'::jsonb, NULL, 'The RBI was established on April 1, 1935, under the Reserve Bank of India Act, 1934.'),
  ('gk-5', 'multiple-choice', 'Which of the following are Fundamental Rights guaranteed under Part III of the Constitution of India? (Select all that apply)', 'General Knowledge', 'Polity', 'Intermediate', '[{"id":"go-17","text":"Right to Equality"},{"id":"go-18","text":"Right to Freedom"},{"id":"go-19","text":"Right to Property"},{"id":"go-20","text":"Right against Exploitation"}]'::jsonb, '["go-17","go-18","go-20"]'::jsonb, NULL, 'Right to Equality, Freedom, and against Exploitation are Fundamental Rights. Right to Property was moved to Article 300A as a legal right in 1978.'),
  ('gk-6', 'multiple-choice', 'Which of the following major Indian rivers originate within the Himalayan mountain system? (Select all that apply)', 'General Knowledge', 'Geography', 'Intermediate', '[{"id":"go-21","text":"Ganga"},{"id":"go-22","text":"Godavari"},{"id":"go-23","text":"Brahmaputra"},{"id":"go-24","text":"Narmada"}]'::jsonb, '["go-21","go-23"]'::jsonb, NULL, 'Ganga and Brahmaputra originate in the Himalayas. Godavari originates in Western Ghats, and Narmada in the Amarkantak plateau.'),
  ('gk-7', 'true-false', 'The Tropic of Cancer (23.5° N latitude) passes through exactly eight states across India.', 'General Knowledge', 'Geography', 'Beginner', NULL, 'true'::jsonb, NULL, 'True. It passes through Gujarat, Rajasthan, MP, Chhattisgarh, Jharkhand, West Bengal, Tripura, and Mizoram.'),
  ('gk-8', 'true-false', 'Sound waves are able to propagate through a complete physical vacuum without requiring any material medium.', 'General Knowledge', 'Science', 'Intermediate', NULL, 'false'::jsonb, NULL, 'False. Sound is a mechanical longitudinal wave requiring a material medium (solid, liquid, or gas) to travel.'),
  ('gk-9', 'short-answer', 'What is the official currency of the United Kingdom?', 'General Knowledge', 'Economy', 'Beginner', NULL, '"Pound Sterling"'::jsonb, '["Pound","Pound Sterling","British Pound","GBP"]'::jsonb, 'The official currency of the United Kingdom is the Pound Sterling (GBP).'),
  ('gk-10', 'fill-blank', 'The chemical symbol for Gold in the periodic table of elements is ___.', 'General Knowledge', 'Science', 'Beginner', NULL, '"Au"'::jsonb, '["Au","AU","aurum"]'::jsonb, 'Gold''s symbol ''Au'' derives from its Latin name ''Aurum'', meaning shining dawn.')
ON CONFLICT (id) DO UPDATE SET
  type = EXCLUDED.type,
  text = EXCLUDED.text,
  subject = EXCLUDED.subject,
  topic = EXCLUDED.topic,
  difficulty = EXCLUDED.difficulty,
  options = EXCLUDED.options,
  correct_answer = EXCLUDED.correct_answer,
  acceptable_answers = EXCLUDED.acceptable_answers,
  explanation = EXCLUDED.explanation;

-- 3. SEED EXAM_QUESTIONS MAPPINGS
INSERT INTO public.exam_questions (exam_id, question_id, section_name, order_index)
VALUES
  ('e1', 'reason-3', 'Reasoning', 0),
  ('e1', 'reason-4', 'Reasoning', 1),
  ('e1', 'reason-6', 'Reasoning', 2),
  ('e1', 'gk-1', 'General Knowledge', 3),
  ('e1', 'gk-5', 'General Knowledge', 4),
  ('e1', 'gk-10', 'General Knowledge', 5),
  ('e1', 'quant-3', 'Quantitative Aptitude', 6),
  ('e1', 'quant-4', 'Quantitative Aptitude', 7),
  ('e1', 'quant-8', 'Quantitative Aptitude', 8),
  ('e1', 'eng-3', 'English', 9),
  ('e1', 'eng-4', 'English', 10),
  ('e1', 'eng-7', 'English', 11),
  ('e2', 'quant-1', 'Quantitative Aptitude', 0),
  ('e2', 'quant-2', 'Quantitative Aptitude', 1),
  ('e2', 'quant-5', 'Quantitative Aptitude', 2),
  ('e2', 'quant-9', 'Quantitative Aptitude', 3),
  ('e2', 'reason-1', 'Reasoning', 4),
  ('e2', 'reason-2', 'Reasoning', 5),
  ('e2', 'reason-5', 'Reasoning', 6),
  ('e2', 'reason-7', 'Reasoning', 7),
  ('e2', 'eng-1', 'English', 8),
  ('e2', 'eng-2', 'English', 9),
  ('e2', 'eng-5', 'English', 10),
  ('e2', 'eng-8', 'English', 11),
  ('e3', 'reason-2', 'Reasoning', 0),
  ('e3', 'reason-5', 'Reasoning', 1),
  ('e3', 'reason-6', 'Reasoning', 2),
  ('e3', 'quant-1', 'Quantitative Aptitude', 3),
  ('e3', 'quant-6', 'Quantitative Aptitude', 4),
  ('e3', 'quant-10', 'Quantitative Aptitude', 5),
  ('e3', 'eng-1', 'English', 6),
  ('e3', 'eng-6', 'English', 7),
  ('e3', 'eng-8', 'English', 8),
  ('p1', 'quant-1', 'Quantitative Aptitude', 0),
  ('p1', 'quant-2', 'Quantitative Aptitude', 1),
  ('p1', 'quant-3', 'Quantitative Aptitude', 2),
  ('p1', 'quant-4', 'Quantitative Aptitude', 3),
  ('p1', 'quant-5', 'Quantitative Aptitude', 4),
  ('p1', 'quant-7', 'Quantitative Aptitude', 5),
  ('p1', 'quant-9', 'Quantitative Aptitude', 6),
  ('p1', 'quant-10', 'Quantitative Aptitude', 7),
  ('p2', 'gk-1', 'General Knowledge', 0),
  ('p2', 'gk-2', 'General Knowledge', 1),
  ('p2', 'gk-3', 'General Knowledge', 2),
  ('p2', 'gk-4', 'General Knowledge', 3),
  ('p2', 'gk-5', 'General Knowledge', 4),
  ('p2', 'gk-7', 'General Knowledge', 5),
  ('p2', 'gk-9', 'General Knowledge', 6),
  ('p2', 'gk-10', 'General Knowledge', 7),
  ('p3', 'reason-1', 'Reasoning', 0),
  ('p3', 'reason-2', 'Reasoning', 1),
  ('p3', 'reason-3', 'Reasoning', 2),
  ('p3', 'reason-4', 'Reasoning', 3),
  ('p3', 'reason-5', 'Reasoning', 4),
  ('p3', 'reason-6', 'Reasoning', 5),
  ('p3', 'reason-7', 'Reasoning', 6),
  ('p3', 'reason-8', 'Reasoning', 7),
  ('p4', 'eng-1', 'English', 0),
  ('p4', 'eng-2', 'English', 1),
  ('p4', 'eng-3', 'English', 2),
  ('p4', 'eng-4', 'English', 3),
  ('p4', 'eng-5', 'English', 4),
  ('p4', 'eng-6', 'English', 5),
  ('p4', 'eng-7', 'English', 6),
  ('p4', 'eng-8', 'English', 7),
  ('p5', 'quant-1', 'Quantitative Aptitude', 0),
  ('p5', 'gk-5', 'General Knowledge', 1),
  ('p5', 'reason-6', 'Reasoning', 2),
  ('p5', 'eng-7', 'English', 3),
  ('p5', 'quant-10', 'Quantitative Aptitude', 4)
ON CONFLICT (exam_id, question_id) DO UPDATE SET
  section_name = EXCLUDED.section_name,
  order_index = EXCLUDED.order_index;
